version: '3'

services:
  nginx-a:
    image: nginx:latest
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./google:/usr/share/nginx/html/google/index.html
    environment:
      VIRTUAL_HOST: 'www.example.local'

networks:
  default:
    external: true
    name: sample-network
